In [4]:
print("🚀 Welcome to AI & Machine Learning")
print("Today I will train my first Machine Learning model.")

🚀 Welcome to AI & Machine Learning
Today I will train my first Machine Learning model.

In [5]:
import pandas as pd
import numpy as np

In [6]:
student_data = {
    "Name": ["Ammu", "Rahul", "Anu", "Arjun", "Neha"],
    "Age": [21, 22, 21, 23, 20],
    "Marks": [92, 75, 88, 95, 81]
}

In [7]:
df = pd.DataFrame(student_data)

df

    Name  Age  Marks
0   Ammu   21     92
1  Rahul   22     75
2    Anu   21     88
3  Arjun   23     95
4   Neha   20     81

In [8]:
df.head()

    Name  Age  Marks
0   Ammu   21     92
1  Rahul   22     75
2    Anu   21     88
3  Arjun   23     95
4   Neha   20     81

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [10]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   21.400000  86.200000
std     1.140175   8.167007
min    20.000000  75.000000
25%    21.000000  81.000000
50%    21.000000  88.000000
75%    22.000000  92.000000
max    23.000000  95.000000